schema_version = "1.0.0"
id = "animeow_anim_linker"
version = "1.0.0"
name = "Animeow Anim Linker"
tagline = "Quick Child Of constraint link, parent switching, and bake animation tool"
maintainer = "Antigravity & Tony Meow"
type = "add-on"
website = "https://github.com/tonynguyen030693/Animeow_Blender_Tool"
tags = ["Animation", "Rigging"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-2.0-or-later",
]
